version: '3.8'

services:
  postgres:
    image: postgis/postgis:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ecumenosuser
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: ecumenos_network_warden_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
